sonar.projectKey=jnctech_carbtrack-au
sonar.organization=jnctech
sonar.sources=app
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py
sonar.exclusions=**/seed/**,**/__pycache__/**
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12
